# Generated by Django 4.1 on 2022-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=62)),
                ('is_complited', models.BooleanField(default=False, verbose_name='выполнено')),
            ],
        ),
    ]
