# Generated by Django 4.1 on 2022-08-10 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='is_complited',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
